name: Deploy to Production (Hostinger)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Setup npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
          
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests (if available)
      run: |
        if [ -f "package.json" ] && grep -q '"test"' package.json; then
          npm test
        else
          echo "No tests configured, skipping..."
        fi
      continue-on-error: true
      
    - name: Create environment file for production
      run: |
        cat > .env.local << EOF
        # Production Environment Variables
        
        # Firebase Configuration
        FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}"
        
        # OpenAI Configuration
        OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        
        # Server Configuration
        PORT=3000
        
        # Production URLs
        VITE_API_URL=https://my.ubora-app.com/api/ai/ask
        VITE_AI_ENDPOINT=https://my.ubora-app.com/api/ai/ask
        VITE_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
        VITE_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
        VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        VITE_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
        VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
        VITE_FIREBASE_VAPID_KEY=${{ secrets.FIREBASE_VAPID_KEY }}
        EOF
        
    - name: Build application for production
      run: |
        npm run build
        
    - name: Create deployment package
      run: |
        # Create a deployment directory
        mkdir -p deploy-package
        
        # Copy built files
        cp -r dist/* deploy-package/
        
        # Create API endpoints for static hosting
        mkdir -p deploy-package/api/ai
        
        # Create health check endpoint
        cat > deploy-package/api/ai/health.php << 'EOF'
        <?php
        header('Content-Type: application/json');
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type, Authorization');
        
        if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
            http_response_code(204);
            exit();
        }
        
        echo json_encode([
            'ok' => true,
            'ts' => time(),
            'service' => 'Ubora AI Backend',
            'version' => '1.0.0',
            'message' => 'API endpoint is accessible'
        ]);
        ?>
        EOF
        
        # Create ask endpoint
        cat > deploy-package/api/ai/ask.php << 'EOF'
        <?php
        header('Content-Type: application/json');
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type, Authorization');
        
        if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
            http_response_code(204);
            exit();
        }
        
        // This is a placeholder - you'll need to implement the actual AI logic
        // or use a separate service for the backend
        echo json_encode([
            'error' => 'Backend service not available',
            'message' => 'This is a static deployment. Backend services need to be hosted separately.',
            'suggestion' => 'Consider using Vercel, Netlify Functions, or a separate Node.js hosting service for the API'
        ]);
        ?>
        EOF
        
        # Create index.php for the api/ai directory
        cat > deploy-package/api/ai/index.php << 'EOF'
        <?php
        header('Content-Type: application/json');
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type, Authorization');
        
        echo json_encode([
            'message' => 'Ubora AI API',
            'endpoints' => [
                'GET /api/ai/health' => 'Health check',
                'POST /api/ai/ask' => 'AI chat endpoint'
            ]
        ]);
        ?>
        EOF
         
        # Create .htaccess for Hostinger
        cat > deploy-package/.htaccess << 'EOF'
        # Enable compression
        <IfModule mod_deflate.c>
            AddOutputFilterByType DEFLATE text/plain
            AddOutputFilterByType DEFLATE text/html
            AddOutputFilterByType DEFLATE text/xml
            AddOutputFilterByType DEFLATE text/css
            AddOutputFilterByType DEFLATE application/xml
            AddOutputFilterByType DEFLATE application/xhtml+xml
            AddOutputFilterByType DEFLATE application/rss+xml
            AddOutputFilterByType DEFLATE application/javascript
            AddOutputFilterByType DEFLATE application/x-javascript
        </IfModule>
        
        # Cache static assets
        <IfModule mod_expires.c>
            ExpiresActive on
            ExpiresByType text/css "access plus 1 year"
            ExpiresByType application/javascript "access plus 1 year"
            ExpiresByType image/png "access plus 1 year"
            ExpiresByType image/jpg "access plus 1 year"
            ExpiresByType image/jpeg "access plus 1 year"
            ExpiresByType image/gif "access plus 1 year"
            ExpiresByType image/svg+xml "access plus 1 year"
        </IfModule>
        
        # Security headers
        <IfModule mod_headers.c>
            Header always set X-Content-Type-Options nosniff
            Header always set X-Frame-Options DENY
            Header always set X-XSS-Protection "1; mode=block"
            Header always set Referrer-Policy "strict-origin-when-cross-origin"
        </IfModule>
        
        # Handle client-side routing
        RewriteEngine On
        RewriteBase /
        
        # Don't rewrite existing files or directories
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule . - [L]
        
        # Handle client-side routing for non-API routes
        RewriteRule ^index\.html$ - [L]
        RewriteRule . /index.html [L]
        EOF
         
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.PROD_FTP_HOST }}
        username: ${{ secrets.PROD_FTP_USERNAME }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        local-dir: ./deploy-package/
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
          **/README.md
          **/.github/**
          
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Production deployment completed successfully!"
        echo "🌐 Application deployed to: https://my.ubora-app.com"
        echo "📊 Build completed at: $(date)"
        
    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Production deployment failed!"
        echo "Please check the logs for more details."
