name: Setup VPS (One-time)

on:
  workflow_dispatch: # Manual trigger only

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup VPS Infrastructure
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          echo "🚀 Starting VPS setup..."
          
          # Update system
          apt update && apt upgrade -y
          
          # Install essential tools
          apt install -y curl wget git unzip software-properties-common
          
          # Install Node.js 18
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
          
          # Install PM2 globally
          npm install -g pm2
          
          # Install Nginx
          apt install -y nginx
          
          # Install UFW firewall
          apt install -y ufw
          
          # Configure firewall
          ufw enable
          ufw allow ssh
          ufw allow 80
          ufw allow 443
          ufw allow 3000
          ufw allow 3001
          
          # Create project directories
          mkdir -p /var/www/ubora-backend-dev
          mkdir -p /var/www/ubora-backend-prod
          chown -R root:root /var/www/ubora-backend-*
          
          # Configure Nginx
          cat > /etc/nginx/sites-available/api-dev.ubora-app.com << 'EOF'
          server {
              listen 80;
              server_name api-dev.ubora-app.com;
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          EOF
          
          cat > /etc/nginx/sites-available/api.ubora-app.com << 'EOF'
          server {
              listen 80;
              server_name api.ubora-app.com;
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_cache_bypass $http_upgrade;
              }
          }
          EOF
          
          # Enable Nginx sites
          ln -sf /etc/nginx/sites-available/api-dev.ubora-app.com /etc/nginx/sites-enabled/
          ln -sf /etc/nginx/sites-available/api.ubora-app.com /etc/nginx/sites-enabled/
          
          # Test and restart Nginx
          nginx -t
          systemctl restart nginx
          systemctl enable nginx
          
          # Install Certbot for SSL
          apt install -y certbot python3-certbot-nginx
          
          echo "✅ VPS setup completed successfully!"
          echo "📋 Next steps:"
          echo "1. Add DNS records for api-dev.ubora-app.com and api.ubora-app.com"
          echo "2. Run SSL setup: certbot --nginx -d api-dev.ubora-app.com -d api.ubora-app.com"
          echo "3. Push to dev/master branches to trigger deployment"

